# Generated by Django 5.2.4 on 2025-07-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0004_rename_posts_user_posts_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Post ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('title', models.CharField(max_length=60, verbose_name='Post Title')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user', verbose_name='Owner Post')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Like ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user', verbose_name='Owner Like')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.posts', verbose_name='Post Liked')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
