# Generated by Django 5.2.4 on 2025-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='Nome de Usuário')),
                ('posts', models.IntegerField(default=0, verbose_name='Quantidade de Posts')),
            ],
        ),
    ]
