# Generated by Django 5.2.4 on 2025-07-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user',
        ),
    ]
