# Generated by Django 5.2.4 on 2025-07-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_username_user_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='posts',
            new_name='posts_counts',
        ),
    ]
