# Generated by Django 5.2.4 on 2025-07-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_posts_user_posts_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
