# Generated by Django 5.2.4 on 2025-07-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts_counts',
        ),
    ]
